# Generated by Django 4.1.3 on 2022-11-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'foundation',
                'ordering': ('-created_at',),
            },
        ),
    ]
